# Generated by Django 6.0.6 on 2026-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_current_runtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
