# Generated by Django 6.0.6 on 2026-07-24 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_metadata_equipment_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
