# Generated by Django 6.0.6 on 2026-07-06 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_current_runtime_hours_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='frequency_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Repeat every X hours', null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='next_due_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='trigger_type',
            field=models.CharField(choices=[('TIME', 'Time-based'), ('USAGE', 'Usage-based')], default='TIME', max_length=10),
        ),
        migrations.AddField(
            model_name='repairtask',
            name='source',
            field=models.CharField(choices=[('PREVENTIVE', 'Preventive Maintenance'), ('REACTIVE', 'Reactive (Breakdown)')], default='REACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='frequency_days',
            field=models.PositiveIntegerField(blank=True, help_text='Repeat every X days', null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DowntimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_logs', to='equipment.equipment')),
                ('repair_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_events', to='maintenance.repairtask')),
            ],
        ),
    ]
