# Generated by Django 6.0.6 on 2026-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='request_photos/'),
        ),
    ]
