# Generated by Django 6.0.6 on 2026-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_repairtask_source_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='ai_suggested_priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='ai_troubleshooting_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
