# Generated by Django 6.0.6 on 2026-07-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_maintenanceteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('TECHNICIAN', 'Technician'), ('WORKER', 'Worker')], default='TECHNICIAN', max_length=20),
        ),
    ]
