# Generated by Django 6.0.6 on 2026-07-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('TECHNICIAN', 'Technician'), ('EMPLOYEE', 'Employee')], default='TECHNICIAN', max_length=20),
        ),
    ]
